<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Digital_Index</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Quarto_Digital_Index_files/libs/clipboard/clipboard.min.js"></script>
<script src="Quarto_Digital_Index_files/libs/quarto-html/quarto.js"></script>
<script src="Quarto_Digital_Index_files/libs/quarto-html/popper.min.js"></script>
<script src="Quarto_Digital_Index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Quarto_Digital_Index_files/libs/quarto-html/anchor.min.js"></script>
<link href="Quarto_Digital_Index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Quarto_Digital_Index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Quarto_Digital_Index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Quarto_Digital_Index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Quarto_Digital_Index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Digital_Index</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="municipality-digitalization-and-local-engagement-the-case-of-chile" class="level1">
<h1>Municipality digitalization and local engagement: The case of Chile</h1>
<p>Pedro Fierro Ellen Helsper</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This paper analyses the elements and contextual factors related to the digitalisation of local governments and examines the impacts of municipal digitalisation on political engagement—both attitudinal and behavioural. Our findings are twofold. First, at the national level, considering 343 local administrations, the results suggest that population size, rurality, municipal income, and professional workforce are associated with the level of digitalisation in each municipality, though these relationships vary by region. In southern Chile, population size and municipal income appear more influential, whereas in central Chile, income and workforce factors play a greater role. Second, based on 9,924 face-to-face cases collected in Chile’s Valparaíso region from 2018 to 2024, results indicate that living in a digitalised municipality positively and meaningfully influences not only the likelihood of using digital services but also the belief that the Internet empowers citizens politically. Conversely, living in a municipality with a wealthy local government shows an opposite relationship, suggesting that it is not necessarily the budget but rather the efforts toward digitalisation that are crucial for enhancing local engagement. These findings are important for understanding democratisation and the role of local government modernisation, as well as for addressing the causes and direct consequences of digital inequalities.</p>
<p><strong>Keywords:</strong> local governments; digital inequalities; democratisation; civic engagement; online participation</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>One of the major challenges faced by both emerging and established democracies is the modernization of local governments, with digitalization as a core component. Digitalization not only aims to make processes more efficient and faster but also seeks to bring the entire state structure closer to individuals, potentially fostering higher levels of civic engagement. Increasingly, research suggests that citizens in “left-behind” areas experience greater political disengagement and negative sentiments toward politics and its processes. Chile, our case study, is no exception, especially given the pronounced centralism that has long shaped the state, resulting in diverse citizen experiences depending on geographic location. Within this context, digitalization has become a priority for policymakers; however, its broader consequences are not always fully appreciated.</p>
<p>This paper has a dual objective. First, it seeks to identify the factors that may explain the digitalisation of local governments. Second, it examines, at an individual level, the effects of these digitalisation processes on political engagement, both in terms of attitudes and behaviours.</p>
<pre><code>To achieve these objectives, we use official data from the Chilean government and the Digital Municipal Index, recently developed by the Millennium Nucleus of Inequalities and Digital Opportunities (NUDOS). Additionally, to analyse the phenomenon at the individual level, we draw on survey data from 9,924 face-to-face interviews conducted by Fundación P! ensa in the Valparaíso region of Chile. Our findings are twofold. First, at the national level, examining 343 local administrations, results suggest that population size, rurality, municipal income, and professional workforce are associated with the level of digitalisation in each municipality, though these relationships vary by region. In southern Chile, population size and municipal income appear more influential, while in central Chile, income and workforce factors are more critical. Second, at the individual level, results indicate that individuals living in a municipality with a digitalised local government are more likely to use official digital services and, more importantly, are more inclined to believe that the Internet empowers citizens politically. Conversely, living in a municipality with a wealthy local government shows an opposite relationship, suggesting that it is not necessarily the budget but rather the efforts toward digitalisation that are crucial for enhancing local engagement.

These findings contribute not only to understanding the causes and consequences of digitalisation processes in an emerging democracy like Chile but also offer insight into the impact of digital inequalities. Since the beginning of the “electronic revolution,” the Internet was envisioned as a tool to transcend physical boundaries and foster the inclusion of politically marginalised areas. Over time, however, the reinforcement thesis—suggesting that offline inequalities are simply replicated online—has gained traction. The results of this study offer pathways for achieving greater inclusion in the digital age.</code></pre>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review">Literature Review</h2>
<section id="digital-inequalities" class="level3">
<h3 class="anchored" data-anchor-id="digital-inequalities">Digital inequalities</h3>
</section>
<section id="local-engagement" class="level3">
<h3 class="anchored" data-anchor-id="local-engagement">Local engagement</h3>
</section>
<section id="case-study" class="level3">
<h3 class="anchored" data-anchor-id="case-study">Case Study</h3>
</section>
</section>
<section id="data-and-methods" class="level2">
<h2 class="anchored" data-anchor-id="data-and-methods">Data and Methods</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>Al data considered in this study is publicly available.</p>
</section>
<section id="municipal-level-data" class="level3">
<h3 class="anchored" data-anchor-id="municipal-level-data">Municipal-Level Data</h3>
<p>First, municipal-level data was considered, covering the 343 mainland municipalities of Chile (excluding Juan Fernández and Easter Island).</p>
<section id="variables" class="level4">
<h4 class="anchored" data-anchor-id="variables">Variables</h4>
<p><strong>Digital Municipality Index</strong>. The level of digitalization was measured using the Digital Municipality Index, developed by the Millennium Nucleus of Inequalities and Digital Opportunities (NUDOS). The index is based on 34 potential services offered by municipal websites. These 34 services were grouped into two categories: “Payments, procedures, and online services,” which includes 13 activities, and “Information and transparency,” which includes 21 activities.</p>
<p><strong>Population</strong>. Population was measured as the projected number of people living in each municipality in 2023, expressed in log terms. The data comes from the National Municipal Information System (SINIM).</p>
<p><strong>Municipal Income</strong>. Municipal income was measured as own-source revenues, meaning the income generated independently by each municipality, expresed in log terms. The data comes from the National Municipal Information System (SINIM).</p>
<p><strong>Rurality</strong>. Rurality was measured as the percentage of the population living in rural areas within each municipality in 2023. This data was also obtained from the National Municipal Information System (SINIM).</p>
<p><strong>Qualified Municipal Workforce</strong>. To capture the professional resources of each municipality, the number of employees with a university degree was considered, expressed in log terms. The data comes from the National Municipal Information System (SINIM).</p>
</section>
</section>
<section id="individual-level-data" class="level3">
<h3 class="anchored" data-anchor-id="individual-level-data">Individual-Level Data</h3>
<p>Secondly, we use data from the Political Opinion Survey (EOP), developed by Fundación P!ensa and conducted with IPSOS and Datavoz-STATCOM. This paper considers seven iterations of the survey from 2018 to 2024, encompassing 9,924 face-to-face interviews conducted in the ten largest cities in the Valparaíso region of Chile. The survey employs a probabilistic, non-proportional design with a three-stage random sampling method (by block, household, and individual), targeting men and women aged 18 and older.</p>
<section id="variables-1" class="level4">
<h4 class="anchored" data-anchor-id="variables-1">Variables</h4>
<p><strong>Online Political Efficacy</strong>. To measure online political efficacy, we follow the approach proposed by Sasaki (2016, 2017), asking respondents to indicate their agreement with the following statements:</p>
<ol type="1">
<li>Using the internet, people like me have more political power.</li>
<li>Using the internet, I can have a greater voice regarding what the government does.</li>
<li>Using the internet, it is easier for me to understand politics.</li>
<li>Using the internet, public officials are more concerned about what I think.</li>
</ol>
<p>Each of these questions was measured on a 5-point Likert scale, where 1 indicated strong disagreement and 5 indicated strong agreement.</p>
<p><strong>Awareness and Use of Municipal Website</strong>. To measure specific uses of the official local government website, respondents were asked to indicate their agreement with the following statements:</p>
<ol type="1">
<li>I am aware of the existence of the municipal website (know_web).</li>
<li>I have used the municipal website to complete administrative procedures and/or make service payments (use_adm).</li>
<li>I have used the municipal website to seek information from the municipality (use_info).</li>
<li>I have used the municipal website to request transparency information (use_transp).</li>
<li>I have used the municipal website for other purposes (use_other). Each of these questions was measured as a dummy variable, coded as 1 for “yes” and 0 otherwise.</li>
</ol>
<p><strong>Living in a Digitalized Municipality</strong>. To examine contextual factors that may influence our variables of interest, we included a variable to determine whether individuals live in a highly or minimally digitalized municipality. Specifically, the value of the Digital Municipality Index (measured at the municipal level) was assigned to individuals based on their place of residence. To prevent misinterpretations and ecological fallacies, it is essential to clarify that this variable represents an individual-level attribute: living in a municipality with a strong digital services offering.</p>
<p><strong>Living in a Wealthy Municipality</strong>. Additionally, we considered the impact of residing in a wealthy municipality. This was measured by assigning the Municipal Income level to individuals based on their municipality of residence. Similar to the previous variable, it is important to emphasize that this measure does not reflect individual income (as we have a separate socioeconomic variable described in the following sections); rather, it captures only the effect of living in a municipality classified as affluent or economically disadvantaged.</p>
<p><strong>Political Interest</strong>. Political interest was measured using a self-reported approach. Specifically, all respondents were asked how interested they were in the following areas:</p>
<ol type="1">
<li>Politics</li>
<li>Issues happening in the world</li>
<li>Issues happening in the country</li>
<li>Issues happening in their region</li>
<li>Issues happening in their neighbourhood</li>
</ol>
<p>Each question was measured on a 4-point Likert scale, where 1 indicated ‘no interest’ and 4 indicated ‘strong interest.’ Using confirmatory factor analysis (CFA), a factor for political interest was constructed from these responses (Cronbach’s alpha: 0.86).</p>
<p><strong>Control Variables</strong> Various sociodemographic variables were included as control variables, such as age, education, gender, and socioeconomic status.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="first-part-analyses-at-the-municipal-level" class="level3">
<h3 class="anchored" data-anchor-id="first-part-analyses-at-the-municipal-level">First Part: Analyses at the municipal level</h3>
<p>First, the analyses focused on the national context, using aggregated data at the municipal level. Starting with a descriptive approach (see Figure 2) to examine the Digital Municipality Index, we observe an apparent relationship between population size, rurality, income, and workforce professionalisation in each municipality. The distribution of the index shows that more urban, densely populated municipalities with a more qualified workforce tend to score higher. However, an inferential approach provides a slightly different perspective. While municipal income appears to be the most important factor explaining a higher digitalisation index, rurality and the formal qualifications of the municipal workforce do not have significant coefficients. Population, though close to significance, also plays a role. Thus, the results suggest that the most populated and wealthiest municipalities tend to offer more digital services to their residents (see Table 1).</p>
<p>Moreover, in the context of a highly centralised country, these results vary when analysing different regions separately. In southern Chile, population size and municipal income appear to be more influential, whereas in central Chile, income and workforce factors play a greater role (see Figure 3).</p>
<p><strong>Figure 1</strong> Digital Municipality Index</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Figure 2</strong>. Dispersion diagram of the Digital Municipality Index, considering population, rurality, municipal income and quaified municipal workforce.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Table 1</strong> OLS for Digital Municipality Index at the municipal level</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Municipio_Digital ~ log_Poblacion.y + Pob_Rural_Porc + 
    log_Ingresos_Propios_Permanentes + log_Num_Planta_Profes, 
    data = merged_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.176363 -0.050995 -0.000819  0.043321  0.220699 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      -0.165083   0.079892  -2.066   0.0397 *  
log_Poblacion.y                   0.016171   0.008789   1.840   0.0669 .  
Pob_Rural_Porc                    0.002764   0.025464   0.109   0.9136    
log_Ingresos_Propios_Permanentes  0.030322   0.006985   4.341 1.99e-05 ***
log_Num_Planta_Profes             0.015231   0.011154   1.366   0.1732    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07304 on 278 degrees of freedom
  (60 observations deleted due to missingness)
Multiple R-squared:  0.4639,    Adjusted R-squared:  0.4562 
F-statistic: 60.15 on 4 and 278 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Municipio_Digital ~ log_Poblacion.y + Pob_Rural_Porc + 
    log_Ingresos_Propios_Permanentes + log_Num_Planta_Profes, 
    data = md_north)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.172945 -0.062475 -0.001547  0.052815  0.181538 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                       0.107520   0.382362   0.281    0.781
log_Poblacion.y                   0.029862   0.030354   0.984    0.336
Pob_Rural_Porc                   -0.019628   0.085000  -0.231    0.820
log_Ingresos_Propios_Permanentes  0.001218   0.036246   0.034    0.973
log_Num_Planta_Profes             0.021216   0.043438   0.488    0.630

Residual standard error: 0.09674 on 22 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.3352,    Adjusted R-squared:  0.2143 
F-statistic: 2.773 on 4 and 22 DF,  p-value: 0.05255</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Municipio_Digital ~ log_Poblacion.y + Pob_Rural_Porc + 
    log_Ingresos_Propios_Permanentes + log_Num_Planta_Profes, 
    data = md_centre)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.154499 -0.058198 -0.006089  0.047512  0.203650 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)                      -0.064568   0.129568  -0.498  0.61907   
log_Poblacion.y                   0.001935   0.012211   0.158  0.87432   
Pob_Rural_Porc                   -0.032916   0.041531  -0.793  0.42944   
log_Ingresos_Propios_Permanentes  0.030329   0.009939   3.051  0.00275 **
log_Num_Planta_Profes             0.032186   0.016297   1.975  0.05034 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07676 on 133 degrees of freedom
  (13 observations deleted due to missingness)
Multiple R-squared:  0.4533,    Adjusted R-squared:  0.4368 
F-statistic: 27.56 on 4 and 133 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Municipio_Digital ~ log_Poblacion.y + Pob_Rural_Porc + 
    log_Ingresos_Propios_Permanentes + log_Num_Planta_Profes, 
    data = md_south)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.165738 -0.034722  0.001215  0.035254  0.187039 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)                      -0.37230    0.11127  -3.346  0.00111 **
log_Poblacion.y                   0.03658    0.01546   2.366  0.01967 * 
Pob_Rural_Porc                    0.03894    0.03369   1.156  0.25018   
log_Ingresos_Propios_Permanentes  0.03756    0.01173   3.201  0.00178 **
log_Num_Planta_Profes            -0.01899    0.01658  -1.145  0.25462   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0624 on 113 degrees of freedom
  (30 observations deleted due to missingness)
Multiple R-squared:  0.5043,    Adjusted R-squared:  0.4868 
F-statistic: 28.74 on 4 and 113 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Figure 3</strong>. OLS for Digital Municipality Index at the municipal level</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="second-part-analyses-at-the-individual-level-chilean-region-of-valparaiso-as-case-study" class="level3">
<h3 class="anchored" data-anchor-id="second-part-analyses-at-the-individual-level-chilean-region-of-valparaiso-as-case-study">Second Part: Analyses at the individual level, Chilean region of Valparaiso as case study</h3>
<p>Secondly, the specific case of the Valparaíso region in Chile was analysed using individual-level data. In this context, the aim was to test whether municipal digitalisation affects online political engagement by examining both attitudinal and behavioural components. The attitudinal component presents a complex picture (see Table 2). Living in a digitalised municipality does not appear to impact online political efficacy—defined as individuals’ beliefs that the internet empowers citizens politically. However, the other contextual factor, living in a wealthy municipality, shows a negative and significant relationship with these attitudes. In other words, individuals in marginalised areas with poorer municipalities tend to view the Internet as a valuable tool for enhancing their political voice.</p>
<p>Interestingly, the influence of a digitalised municipality changes when analysing specific measures of online political efficacy. Specifically, results indicate that the digitalisation of local government has a positive and significant relationship with OPE1, or the belief that “by using the internet, people like me have more political power.”</p>
<p>Regarding the behavioural dimension of online local participation, the results are consistent and robust (see Table 3). Living in a digitalised municipality has a positive and significant relationship with all measures of awareness and use of the official municipal website, a pattern not observed for residents of wealthy municipalities. In fact, while the relationship with living in a wealthy municipality is significant, it is in the opposite direction. In other words, the results suggest that it is not necessarily the budget but rather the efforts toward digitalisation that are crucial for enhancing local engagement.</p>
<p><strong>Table 2</strong> OLS for Online Political Efficacy at the Individual Level</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope ~ dig_mun + ingresos + sex + age + SES + education + 
    intpol + factor(year), data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.08622 -0.58347 -0.02698  0.60450  2.74480 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.2999464  0.1682358   1.783 0.074638 .  
dig_mun           0.1589623  0.1185248   1.341 0.179899    
ingresos         -0.0255358  0.0124663  -2.048 0.040551 *  
sex              -0.1220766  0.0178198  -6.851 7.85e-12 ***
age              -0.0053489  0.0005332 -10.031  &lt; 2e-16 ***
SES               0.0337665  0.0119061   2.836 0.004578 ** 
education         0.0182781  0.0054471   3.356 0.000795 ***
intpol            0.3904303  0.0193647  20.162  &lt; 2e-16 ***
factor(year)2019  0.0394652  0.0304665   1.295 0.195230    
factor(year)2020  0.1795567  0.0308274   5.825 5.93e-09 ***
factor(year)2021  0.2359294  0.0305832   7.714 1.35e-14 ***
factor(year)2022  0.1635415  0.0303031   5.397 6.96e-08 ***
factor(year)2023  0.1761850  0.0308267   5.715 1.13e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8152 on 8774 degrees of freedom
Multiple R-squared:  0.1021,    Adjusted R-squared:  0.1009 
F-statistic: 83.13 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope1 ~ dig_mun + ingresos + sex + age + SES + education + 
    intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2998 -0.8246 -0.2290  0.9393  3.3471 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       2.5749293  0.2390494  10.772  &lt; 2e-16 ***
dig_mun           0.3660069  0.1684141   2.173 0.029788 *  
ingresos         -0.0234007  0.0177135  -1.321 0.186516    
sex              -0.1458139  0.0253206  -5.759 8.76e-09 ***
age              -0.0043026  0.0007577  -5.679 1.40e-08 ***
SES               0.0436412  0.0169176   2.580 0.009907 ** 
education         0.0223558  0.0077398   2.888 0.003881 ** 
intpol            0.4222330  0.0275157  15.345  &lt; 2e-16 ***
factor(year)2019  0.0193999  0.0432905   0.448 0.654068    
factor(year)2020  0.1713444  0.0438033   3.912 9.23e-05 ***
factor(year)2021  0.2576296  0.0434563   5.928 3.17e-09 ***
factor(year)2022  0.1484448  0.0430583   3.448 0.000568 ***
factor(year)2023  0.1629771  0.0438023   3.721 0.000200 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.158 on 8774 degrees of freedom
Multiple R-squared:  0.06238,   Adjusted R-squared:  0.0611 
F-statistic: 48.64 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope2 ~ dig_mun + ingresos + sex + age + SES + education + 
    intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5974 -0.9203 -0.0625  1.0009  3.2119 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       3.1296660  0.2452538  12.761  &lt; 2e-16 ***
dig_mun           0.1533807  0.1727852   0.888  0.37473    
ingresos         -0.0267314  0.0181733  -1.471  0.14135    
sex              -0.1553894  0.0259777  -5.982 2.30e-09 ***
age              -0.0067836  0.0007773  -8.727  &lt; 2e-16 ***
SES               0.0345152  0.0173567   1.989  0.04678 *  
education         0.0209707  0.0079407   2.641  0.00828 ** 
intpol            0.5013142  0.0282299  17.758  &lt; 2e-16 ***
factor(year)2019  0.0673183  0.0444141   1.516  0.12963    
factor(year)2020  0.2482294  0.0449402   5.524 3.42e-08 ***
factor(year)2021  0.3016648  0.0445841   6.766 1.41e-11 ***
factor(year)2022  0.2228076  0.0441758   5.044 4.66e-07 ***
factor(year)2023  0.2078361  0.0449392   4.625 3.80e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.188 on 8774 degrees of freedom
Multiple R-squared:  0.07744,   Adjusted R-squared:  0.07617 
F-statistic: 61.37 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope3 ~ dig_mun + ingresos + sex + age + SES + education + 
    intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1327 -0.8759  0.1353  0.8867  3.3551 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       3.686999   0.237588  15.518  &lt; 2e-16 ***
dig_mun           0.194766   0.167384   1.164 0.244623    
ingresos         -0.040672   0.017605  -2.310 0.020900 *  
sex              -0.160489   0.025166  -6.377 1.89e-10 ***
age              -0.014171   0.000753 -18.819  &lt; 2e-16 ***
SES               0.043047   0.016814   2.560 0.010479 *  
education         0.037125   0.007692   4.826 1.42e-06 ***
intpol            0.515888   0.027348  18.864  &lt; 2e-16 ***
factor(year)2019  0.153620   0.043026   3.570 0.000358 ***
factor(year)2020  0.339778   0.043535   7.805 6.65e-15 ***
factor(year)2021  0.480366   0.043191  11.122  &lt; 2e-16 ***
factor(year)2022  0.394308   0.042795   9.214  &lt; 2e-16 ***
factor(year)2023  0.428002   0.043534   9.831  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.151 on 8774 degrees of freedom
Multiple R-squared:  0.1402,    Adjusted R-squared:  0.139 
F-statistic: 119.2 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope4 ~ dig_mun + ingresos + sex + age + SES + education + 
    intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9118 -0.7808 -0.2592  0.7084  3.2886 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       2.9435991  0.2303437  12.779  &lt; 2e-16 ***
dig_mun          -0.0189933  0.1622808  -0.117  0.90683    
ingresos         -0.0408788  0.0170685  -2.395  0.01664 *  
sex              -0.0968831  0.0243984  -3.971 7.22e-05 ***
age              -0.0003039  0.0007301  -0.416  0.67721    
SES               0.0462905  0.0163015   2.840  0.00453 ** 
education         0.0062274  0.0074580   0.835  0.40374    
intpol            0.3693468  0.0265137  13.930  &lt; 2e-16 ***
factor(year)2019 -0.0769218  0.0417139  -1.844  0.06521 .  
factor(year)2020  0.0508666  0.0422080   1.205  0.22818    
factor(year)2021  0.0447508  0.0418737   1.069  0.28523    
factor(year)2022 -0.0211127  0.0414902  -0.509  0.61086    
factor(year)2023  0.0586797  0.0422071   1.390  0.16448    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.116 on 8774 degrees of freedom
Multiple R-squared:  0.03653,   Adjusted R-squared:  0.03521 
F-statistic: 27.72 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Table 3</strong> OLS for Effective Municipality Webpage use at the Individual Level</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useweb_nona ~ dig_mun + ingresos + sex + age + 
    SES + education + ope1 + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.0151  -0.9205  -0.5161   1.0090   2.6141  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       1.306415   0.467816   2.793 0.005229 ** 
dig_mun           2.056890   0.331425   6.206 5.43e-10 ***
ingresos         -0.257945   0.034726  -7.428 1.10e-13 ***
sex               0.170057   0.049448   3.439 0.000584 ***
age              -0.020641   0.001494 -13.819  &lt; 2e-16 ***
SES               0.066741   0.032319   2.065 0.038915 *  
education         0.277936   0.015228  18.252  &lt; 2e-16 ***
ope1              0.028766   0.020738   1.387 0.165400    
intpol            0.752355   0.056879  13.227  &lt; 2e-16 ***
factor(year)2019  0.147328   0.085005   1.733 0.083066 .  
factor(year)2020  0.068736   0.085879   0.800 0.423490    
factor(year)2021  0.324366   0.084925   3.819 0.000134 ***
factor(year)2022  0.003948   0.084860   0.047 0.962892    
factor(year)2023  0.303618   0.085354   3.557 0.000375 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11864  on 8786  degrees of freedom
Residual deviance: 10108  on 8773  degrees of freedom
AIC: 10136

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useadm_nona ~ dig_mun + ingresos + sex + age + 
    SES + education + ope1 + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.7231  -0.7636  -0.5196  -0.2319   2.7712  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -0.574362   0.521443  -1.101   0.2707    
dig_mun           2.083200   0.371956   5.601 2.14e-08 ***
ingresos         -0.206229   0.038653  -5.335 9.53e-08 ***
sex              -0.075598   0.054135  -1.396   0.1626    
age              -0.014225   0.001677  -8.482  &lt; 2e-16 ***
SES               0.061421   0.035217   1.744   0.0811 .  
education         0.247592   0.016989  14.573  &lt; 2e-16 ***
ope1             -0.035982   0.022897  -1.571   0.1161    
intpol            0.671800   0.064491  10.417  &lt; 2e-16 ***
factor(year)2019  0.492210   0.100937   4.876 1.08e-06 ***
factor(year)2020  0.210630   0.103396   2.037   0.0416 *  
factor(year)2021  0.780177   0.098686   7.906 2.67e-15 ***
factor(year)2022  0.505521   0.100600   5.025 5.03e-07 ***
factor(year)2023  0.887367   0.098919   8.971  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9705.7  on 8786  degrees of freedom
Residual deviance: 8605.9  on 8773  degrees of freedom
AIC: 8633.9

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useinfo_nona ~ dig_mun + ingresos + sex + age + 
    SES + education + ope1 + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.7741  -0.8497  -0.5443   1.0521   2.7495  

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       0.63429    0.48811   1.299  0.19378    
dig_mun           1.85171    0.34530   5.363 8.20e-08 ***
ingresos         -0.23748    0.03623  -6.555 5.57e-11 ***
sex               0.23114    0.05140   4.497 6.89e-06 ***
age              -0.01940    0.00157 -12.360  &lt; 2e-16 ***
SES               0.01982    0.03312   0.598  0.54967    
education         0.25557    0.01581  16.169  &lt; 2e-16 ***
ope1              0.02494    0.02140   1.166  0.24380    
intpol            0.86090    0.06058  14.210  &lt; 2e-16 ***
factor(year)2019  0.49708    0.09012   5.516 3.47e-08 ***
factor(year)2020  0.14004    0.09204   1.522  0.12813    
factor(year)2021  0.49050    0.09002   5.449 5.08e-08 ***
factor(year)2022  0.27001    0.09082   2.973  0.00295 ** 
factor(year)2023  0.57455    0.09043   6.354 2.10e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 10948.0  on 8786  degrees of freedom
Residual deviance:  9523.3  on 8773  degrees of freedom
AIC: 9551.3

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = usetransp_nona ~ dig_mun + ingresos + sex + age + 
    SES + education + ope1 + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.2299  -0.5696  -0.4249  -0.2850   2.8501  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       1.633974   0.665076   2.457   0.0140 *  
dig_mun           1.069156   0.457134   2.339   0.0193 *  
ingresos         -0.241556   0.049454  -4.884 1.04e-06 ***
sex               0.147258   0.068408   2.153   0.0313 *  
age              -0.020381   0.002154  -9.461  &lt; 2e-16 ***
SES              -0.046090   0.043064  -1.070   0.2845    
education         0.157290   0.020859   7.541 4.67e-14 ***
ope1              0.058646   0.028087   2.088   0.0368 *  
intpol            0.989913   0.084603  11.701  &lt; 2e-16 ***
factor(year)2019 -0.503057   0.109536  -4.593 4.38e-06 ***
factor(year)2020 -0.781370   0.113384  -6.891 5.53e-12 ***
factor(year)2021 -0.647076   0.110823  -5.839 5.26e-09 ***
factor(year)2022 -0.690701   0.112345  -6.148 7.85e-10 ***
factor(year)2023 -0.618932   0.113761  -5.441 5.31e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6654.8  on 8786  degrees of freedom
Residual deviance: 6113.8  on 8773  degrees of freedom
AIC: 6141.8

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useother_nona ~ dig_mun + ingresos + sex + age + 
    SES + education + ope1 + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.3795  -0.5624  -0.3880  -0.2477   2.9198  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       1.331142   0.685510   1.942   0.0522 .  
dig_mun           3.214071   0.482013   6.668 2.59e-11 ***
ingresos         -0.398382   0.051312  -7.764 8.23e-15 ***
sex               0.143944   0.069210   2.080   0.0375 *  
age              -0.017192   0.002172  -7.914 2.49e-15 ***
SES              -0.004507   0.043563  -0.103   0.9176    
education         0.213426   0.021467   9.942  &lt; 2e-16 ***
ope1              0.069480   0.028688   2.422   0.0154 *  
intpol            0.868800   0.085585  10.151  &lt; 2e-16 ***
factor(year)2019  0.767684   0.121713   6.307 2.84e-10 ***
factor(year)2020  0.006236   0.131760   0.047   0.9622    
factor(year)2021  0.068629   0.130821   0.525   0.5999    
factor(year)2022 -0.211674   0.138773  -1.525   0.1272    
factor(year)2023  0.945005   0.120505   7.842 4.43e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6643.2  on 8786  degrees of freedom
Residual deviance: 5904.9  on 8773  degrees of freedom
AIC: 5932.9

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = use ~ dig_mun + ingresos + sex + age + SES + education + 
    ope1 + intpol + factor(year), data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43088 -0.17654 -0.07123  0.17153  0.76188 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.2084018  0.0491781   4.238 2.28e-05 ***
dig_mun           0.2159999  0.0344292   6.274 3.69e-10 ***
ingresos         -0.0283480  0.0036206  -7.830 5.46e-15 ***
sex               0.0168918  0.0051847   3.258  0.00113 ** 
age              -0.0018655  0.0001551 -12.025  &lt; 2e-16 ***
SES               0.0021452  0.0034589   0.620  0.53515    
education         0.0269956  0.0015826  17.058  &lt; 2e-16 ***
ope1              0.0038472  0.0021819   1.763  0.07789 .  
intpol            0.0889216  0.0056985  15.604  &lt; 2e-16 ***
factor(year)2019  0.0443900  0.0088477   5.017 5.35e-07 ***
factor(year)2020  0.0036729  0.0089602   0.410  0.68188    
factor(year)2021  0.0431542  0.0088992   4.849 1.26e-06 ***
factor(year)2022  0.0156706  0.0088061   1.780  0.07519 .  
factor(year)2023  0.0614807  0.0089592   6.862 7.24e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2367 on 8773 degrees of freedom
Multiple R-squared:  0.1635,    Adjusted R-squared:  0.1623 
F-statistic: 131.9 on 13 and 8773 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>[The results are consistent with previous literature. Marginalised areas—those with poorer municipalities—tend to view the Internet as a useful tool and are more likely to engage. At the same time, municipal digitalisation significantly impacts this engagement, which goes beyond simply requesting documents and completing administrative tasks to include accountability and accessing municipal information. It’s not about wealthy municipalities but rather about those that make an effort to digitalise.]</p>
<section id="individual-analysis---to-report" class="level5">
<h5 class="anchored" data-anchor-id="individual-analysis---to-report">INDIVIDUAL ANALYSIS - TO REPORT</h5>
</section>
</section>
<section id="testing-with-real-income-2018-2023" class="level2">
<h2 class="anchored" data-anchor-id="testing-with-real-income-2018-2023">Testing with real income 2018-2023</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>modela_mean <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + factor(year), data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.08658 -0.58395 -0.02749  0.60391  2.74579 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.3138541  0.1621377   1.936 0.052933 .  
dig_mun            0.1836980  0.1213143   1.514 0.130003    
log_ingresos_real -0.0279262  0.0124830  -2.237 0.025302 *  
sex               -0.1221419  0.0178191  -6.855 7.64e-12 ***
age               -0.0053530  0.0005332 -10.039  &lt; 2e-16 ***
SES                0.0337390  0.0119056   2.834 0.004609 ** 
education          0.0183040  0.0054467   3.361 0.000781 ***
intpol             0.3904228  0.0193634  20.163  &lt; 2e-16 ***
factor(year)2019   0.0402180  0.0304669   1.320 0.186851    
factor(year)2020   0.1766173  0.0308558   5.724 1.07e-08 ***
factor(year)2021   0.2358038  0.0305821   7.711 1.39e-14 ***
factor(year)2022   0.1687303  0.0303879   5.553 2.90e-08 ***
factor(year)2023   0.1861565  0.0311285   5.980 2.31e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8151 on 8774 degrees of freedom
Multiple R-squared:  0.1022,    Adjusted R-squared:  0.1009 
F-statistic:  83.2 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>modelb_mean <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope1 <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelb_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope1 ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3030 -0.8243 -0.2276  0.9383  3.3460 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.5540347  0.2303965  11.085  &lt; 2e-16 ***
dig_mun            0.3681049  0.1723867   2.135 0.032761 *  
log_ingresos_real -0.0227264  0.0177382  -1.281 0.200154    
sex               -0.1458109  0.0253208  -5.759 8.77e-09 ***
age               -0.0043021  0.0007577  -5.678 1.41e-08 ***
SES                0.0436365  0.0169178   2.579 0.009915 ** 
education          0.0223831  0.0077398   2.892 0.003838 ** 
intpol             0.4221601  0.0275152  15.343  &lt; 2e-16 ***
factor(year)2019   0.0200151  0.0432932   0.462 0.643866    
factor(year)2020   0.1689619  0.0438458   3.854 0.000117 ***
factor(year)2021   0.2575875  0.0434570   5.927 3.19e-09 ***
factor(year)2022   0.1526748  0.0431810   3.536 0.000409 ***
factor(year)2023   0.1711198  0.0442334   3.869 0.000110 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.158 on 8774 degrees of freedom
Multiple R-squared:  0.06237,   Adjusted R-squared:  0.06108 
F-statistic: 48.63 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>modelc_mean <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope2 <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelc_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope2 ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5953 -0.9207 -0.0641  1.0007  3.2165 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        3.1736530  0.2363630  13.427  &lt; 2e-16 ***
dig_mun            0.1972689  0.1768510   1.115   0.2647    
log_ingresos_real -0.0317399  0.0181976  -1.744   0.0812 .  
sex               -0.1555127  0.0259766  -5.987 2.23e-09 ***
age               -0.0067916  0.0007773  -8.737  &lt; 2e-16 ***
SES                0.0344686  0.0173559   1.986   0.0471 *  
education          0.0209949  0.0079402   2.644   0.0082 ** 
intpol             0.5013642  0.0282278  17.761  &lt; 2e-16 ***
factor(year)2019   0.0681716  0.0444144   1.535   0.1248    
factor(year)2020   0.2448802  0.0449813   5.444 5.35e-08 ***
factor(year)2021   0.3014695  0.0445824   6.762 1.45e-11 ***
factor(year)2022   0.2286985  0.0442993   5.163 2.49e-07 ***
factor(year)2023   0.2191450  0.0453789   4.829 1.39e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.188 on 8774 degrees of freedom
Multiple R-squared:  0.07753,   Adjusted R-squared:  0.07627 
F-statistic: 61.45 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>modeld_mean <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope3 <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeld_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope3 ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1359 -0.8768  0.1362  0.8874  3.3583 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        3.735472   0.228964  16.315  &lt; 2e-16 ***
dig_mun            0.250258   0.171315   1.461  0.14410    
log_ingresos_real -0.046720   0.017628  -2.650  0.00806 ** 
sex               -0.160642   0.025163  -6.384 1.81e-10 ***
age               -0.014181   0.000753 -18.833  &lt; 2e-16 ***
SES                0.042987   0.016813   2.557  0.01058 *  
education          0.037164   0.007692   4.832 1.38e-06 ***
intpol             0.515928   0.027344  18.868  &lt; 2e-16 ***
factor(year)2019   0.154877   0.043024   3.600  0.00032 ***
factor(year)2020   0.334852   0.043573   7.685 1.70e-14 ***
factor(year)2021   0.480109   0.043187  11.117  &lt; 2e-16 ***
factor(year)2022   0.402983   0.042913   9.391  &lt; 2e-16 ***
factor(year)2023   0.444662   0.043958  10.116  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.151 on 8774 degrees of freedom
Multiple R-squared:  0.1403,    Adjusted R-squared:  0.1392 
F-statistic: 119.3 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>modele_mean <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope4 <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope4 ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + factor(year), data = EOP_nona)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9109 -0.7779 -0.2593  0.7073  3.2894 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.9125946  0.2220073  13.119  &lt; 2e-16 ***
dig_mun           -0.0119673  0.1661097  -0.072  0.94257    
log_ingresos_real -0.0401690  0.0170923  -2.350  0.01879 *  
sex               -0.0968882  0.0243989  -3.971 7.21e-05 ***
age               -0.0003038  0.0007301  -0.416  0.67739    
SES                0.0462790  0.0163018   2.839  0.00454 ** 
education          0.0062745  0.0074580   0.841  0.40020    
intpol             0.3692303  0.0265133  13.926  &lt; 2e-16 ***
factor(year)2019  -0.0758348  0.0417168  -1.818  0.06912 .  
factor(year)2020   0.0466537  0.0422493   1.104  0.26952    
factor(year)2021   0.0446653  0.0418746   1.067  0.28616    
factor(year)2022  -0.0136376  0.0416087  -0.328  0.74310    
factor(year)2023   0.0730669  0.0426228   1.714  0.08651 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.116 on 8774 degrees of freedom
Multiple R-squared:  0.0365,    Adjusted R-squared:  0.03518 
F-statistic:  27.7 on 12 and 8774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>modelf_nona_real <span class="ot">&lt;-</span> <span class="fu">glm</span>(useweb_nona <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona, <span class="at">family =</span> binomial)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelf_nona_real)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useweb_nona ~ dig_mun + log_ingresos_real + sex + 
    age + SES + education + ope + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.0390  -0.9170  -0.5129   1.0072   2.6165  

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        1.180100   0.448436   2.632 0.008499 ** 
dig_mun            2.107829   0.339595   6.207 5.40e-10 ***
log_ingresos_real -0.253695   0.034820  -7.286 3.19e-13 ***
sex                0.176164   0.049505   3.559 0.000373 ***
age               -0.020295   0.001499 -13.540  &lt; 2e-16 ***
SES                0.065282   0.032318   2.020 0.043384 *  
education          0.277412   0.015226  18.219  &lt; 2e-16 ***
ope                0.085168   0.029654   2.872 0.004078 ** 
intpol             0.730417   0.057367  12.732  &lt; 2e-16 ***
factor(year)2019   0.151036   0.085034   1.776 0.075702 .  
factor(year)2020   0.031658   0.086079   0.368 0.713044    
factor(year)2021   0.310666   0.085061   3.652 0.000260 ***
factor(year)2022   0.040663   0.085198   0.477 0.633164    
factor(year)2023   0.383481   0.086332   4.442 8.92e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11864  on 8786  degrees of freedom
Residual deviance: 10104  on 8773  degrees of freedom
AIC: 10132

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>modelg_nona_real <span class="ot">&lt;-</span> <span class="fu">glm</span>(useadm_nona <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona, <span class="at">family =</span> binomial)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelg_nona_real)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useadm_nona ~ dig_mun + log_ingresos_real + sex + 
    age + SES + education + ope + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.6847  -0.7635  -0.5186  -0.2322   2.7603  

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -0.699841   0.501788  -1.395   0.1631    
dig_mun            2.159166   0.381490   5.660 1.52e-08 ***
log_ingresos_real -0.211273   0.038892  -5.432 5.56e-08 ***
sex               -0.066125   0.054179  -1.220   0.2223    
age               -0.013808   0.001681  -8.213  &lt; 2e-16 ***
SES                0.057807   0.035205   1.642   0.1006    
education          0.246204   0.016983  14.497  &lt; 2e-16 ***
ope                0.035195   0.032909   1.069   0.2849    
intpol             0.640133   0.064984   9.851  &lt; 2e-16 ***
factor(year)2019   0.493368   0.100944   4.888 1.02e-06 ***
factor(year)2020   0.173136   0.103629   1.671   0.0948 .  
factor(year)2021   0.758297   0.098776   7.677 1.63e-14 ***
factor(year)2022   0.531488   0.100927   5.266 1.39e-07 ***
factor(year)2023   0.949236   0.099957   9.496  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9705.7  on 8786  degrees of freedom
Residual deviance: 8606.0  on 8773  degrees of freedom
AIC: 8634

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>modelh_nona_real <span class="ot">&lt;-</span> <span class="fu">glm</span>(useinfo_nona <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona, <span class="at">family =</span> binomial)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelh_nona_real)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useinfo_nona ~ dig_mun + log_ingresos_real + sex + 
    age + SES + education + ope + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.7925  -0.8491  -0.5412   1.0510   2.7287  

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        0.546771   0.468594   1.167 0.243278    
dig_mun            1.911490   0.354132   5.398 6.75e-08 ***
log_ingresos_real -0.236131   0.036385  -6.490 8.60e-11 ***
sex                0.240881   0.051482   4.679 2.88e-06 ***
age               -0.018900   0.001575 -12.002  &lt; 2e-16 ***
SES                0.017189   0.033125   0.519 0.603825    
education          0.254644   0.015807  16.109  &lt; 2e-16 ***
ope                0.109420   0.030800   3.553 0.000381 ***
intpol             0.828040   0.061062  13.561  &lt; 2e-16 ***
factor(year)2019   0.499508   0.090183   5.539 3.04e-08 ***
factor(year)2020   0.099366   0.092301   1.077 0.281682    
factor(year)2021   0.469426   0.090191   5.205 1.94e-07 ***
factor(year)2022   0.298602   0.091204   3.274 0.001060 ** 
factor(year)2023   0.643653   0.091505   7.034 2.01e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 10948.0  on 8786  degrees of freedom
Residual deviance:  9512.4  on 8773  degrees of freedom
AIC: 9540.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>modeli_nona_real <span class="ot">&lt;-</span> <span class="fu">glm</span>(usetransp_nona <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona, <span class="at">family =</span> binomial)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeli_nona_real)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = usetransp_nona ~ dig_mun + log_ingresos_real + 
    sex + age + SES + education + ope + intpol + factor(year), 
    family = binomial, data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.2653  -0.5700  -0.4233  -0.2849   2.8618  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        1.34841    0.62867   2.145  0.03196 *  
dig_mun            0.99775    0.46824   2.131  0.03310 *  
log_ingresos_real -0.21803    0.04899  -4.451 8.55e-06 ***
sex                0.15498    0.06848   2.263  0.02363 *  
age               -0.01990    0.00216  -9.214  &lt; 2e-16 ***
SES               -0.04779    0.04304  -1.110  0.26679    
education          0.15674    0.02086   7.515 5.71e-14 ***
ope                0.13298    0.04086   3.255  0.00113 ** 
intpol             0.96316    0.08521  11.304  &lt; 2e-16 ***
factor(year)2019  -0.50011    0.10961  -4.563 5.05e-06 ***
factor(year)2020  -0.81633    0.11378  -7.175 7.25e-13 ***
factor(year)2021  -0.66333    0.11106  -5.973 2.33e-09 ***
factor(year)2022  -0.66299    0.11278  -5.879 4.14e-09 ***
factor(year)2023  -0.55302    0.11517  -4.802 1.57e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6654.8  on 8786  degrees of freedom
Residual deviance: 6111.4  on 8773  degrees of freedom
AIC: 6139.4

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>modelj_nona_real <span class="ot">&lt;-</span> <span class="fu">glm</span>(useother_nona <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona, <span class="at">family =</span> binomial)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelj_nona_real)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = useother_nona ~ dig_mun + log_ingresos_real + sex + 
    age + SES + education + ope + intpol + factor(year), family = binomial, 
    data = EOP_nona)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.3631  -0.5627  -0.3901  -0.2473   2.9316  

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        1.218495   0.653695   1.864   0.0623 .  
dig_mun            3.324581   0.495082   6.715 1.88e-11 ***
log_ingresos_real -0.394456   0.051216  -7.702 1.34e-14 ***
sex                0.143215   0.069221   2.069   0.0385 *  
age               -0.017069   0.002179  -7.834 4.72e-15 ***
SES               -0.003923   0.043532  -0.090   0.9282    
education          0.213807   0.021461   9.963  &lt; 2e-16 ***
ope                0.090065   0.041931   2.148   0.0317 *  
intpol             0.864697   0.086263  10.024  &lt; 2e-16 ***
factor(year)2019   0.779939   0.121816   6.403 1.53e-10 ***
factor(year)2020  -0.028504   0.131926  -0.216   0.8289    
factor(year)2021   0.070690   0.130925   0.540   0.5892    
factor(year)2022  -0.141092   0.139130  -1.014   0.3105    
factor(year)2023   1.083259   0.122386   8.851  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6643.2  on 8786  degrees of freedom
Residual deviance: 5907.4  on 8773  degrees of freedom
AIC: 5935.4

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>modelk_nona_real <span class="ot">&lt;-</span> <span class="fu">lm</span>(use <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> <span class="fu">factor</span>(year), <span class="at">data =</span> EOP_nona)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelk_nona_real)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = use ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + ope + intpol + factor(year), data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43800 -0.17622 -0.06981  0.17207  0.76358 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.1956788  0.0470681   4.157 3.25e-05 ***
dig_mun            0.2217469  0.0352143   6.297 3.18e-10 ***
log_ingresos_real -0.0278394  0.0036240  -7.682 1.74e-14 ***
sex                0.0178051  0.0051856   3.434 0.000598 ***
age               -0.0018173  0.0001556 -11.676  &lt; 2e-16 ***
SES                0.0018937  0.0034570   0.548 0.583852    
education          0.0268919  0.0015819  17.000  &lt; 2e-16 ***
ope                0.0121413  0.0030985   3.918 8.98e-05 ***
intpol             0.0857302  0.0057487  14.913  &lt; 2e-16 ***
factor(year)2019   0.0447386  0.0088434   5.059 4.30e-07 ***
factor(year)2020  -0.0007684  0.0089721  -0.086 0.931751    
factor(year)2021   0.0412170  0.0089060   4.628 3.75e-06 ***
factor(year)2022   0.0194362  0.0088351   2.200 0.027842 *  
factor(year)2023   0.0699375  0.0090530   7.725 1.24e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2366 on 8773 degrees of freedom
Multiple R-squared:  0.1646,    Adjusted R-squared:  0.1633 
F-statistic: 132.9 on 13 and 8773 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a binary variable for pre- and post-pandemic</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>EOP_nona<span class="sc">$</span>post_pandemic <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(EOP_nona<span class="sc">$</span>year <span class="sc">&lt;=</span> <span class="dv">2020</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>modela_pan <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> post_pandemic, <span class="at">data =</span> EOP_nona)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela_pan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + post_pandemic, data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.10169 -0.58404 -0.02881  0.60523  2.86863 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.4683538  0.1592633   2.941  0.00328 ** 
dig_mun            0.2304143  0.1206761   1.909  0.05625 .  
log_ingresos_real -0.0351266  0.0123432  -2.846  0.00444 ** 
sex               -0.1205735  0.0178380  -6.759 1.47e-11 ***
age               -0.0053217  0.0005336  -9.974  &lt; 2e-16 ***
SES                0.0338740  0.0119170   2.842  0.00449 ** 
education          0.0187347  0.0054572   3.433  0.00060 ***
intpol             0.4041870  0.0192557  20.991  &lt; 2e-16 ***
post_pandemic      0.1254509  0.0176213   7.119 1.17e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8169 on 8778 degrees of freedom
Multiple R-squared:  0.09793,   Adjusted R-squared:  0.09711 
F-statistic: 119.1 on 8 and 8778 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>modela_pan_int1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> post_pandemic <span class="sc">+</span> log_ingresos_real <span class="sc">*</span> post_pandemic , <span class="at">data =</span> EOP_nona)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela_pan_int1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + post_pandemic + log_ingresos_real * 
    post_pandemic, data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.13048 -0.57836 -0.02439  0.60081  2.85978 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      1.0018357  0.2073626   4.831 1.38e-06 ***
dig_mun                          0.2292225  0.1205729   1.901 0.057320 .  
log_ingresos_real               -0.0678727  0.0147885  -4.590 4.50e-06 ***
sex                             -0.1200441  0.0178231  -6.735 1.74e-11 ***
age                             -0.0053302  0.0005331  -9.999  &lt; 2e-16 ***
SES                              0.0341294  0.0119070   2.866 0.004162 ** 
education                        0.0186375  0.0054526   3.418 0.000633 ***
intpol                           0.4058642  0.0192437  21.091  &lt; 2e-16 ***
post_pandemic                   -0.9708419  0.2737936  -3.546 0.000393 ***
log_ingresos_real:post_pandemic  0.0669685  0.0166904   4.012 6.06e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8162 on 8777 degrees of freedom
Multiple R-squared:  0.09958,   Adjusted R-squared:  0.09866 
F-statistic: 107.9 on 9 and 8777 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>modela_pan_int2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ope <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> intpol <span class="sc">+</span> post_pandemic <span class="sc">+</span> dig_mun <span class="sc">*</span> post_pandemic , <span class="at">data =</span> EOP_nona)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela_pan_int2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ope ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + intpol + post_pandemic + dig_mun * post_pandemic, 
    data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.11923 -0.58031 -0.02571  0.60281  2.85031 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            0.5579437  0.1667286   3.346 0.000822 ***
dig_mun                0.0762032  0.1476112   0.516 0.605698    
log_ingresos_real     -0.0344183  0.0123477  -2.787 0.005324 ** 
sex                   -0.1208453  0.0178363  -6.775 1.32e-11 ***
age                   -0.0053251  0.0005335  -9.982  &lt; 2e-16 ***
SES                    0.0337035  0.0119158   2.828 0.004688 ** 
education              0.0187279  0.0054565   3.432 0.000601 ***
intpol                 0.4045632  0.0192543  21.012  &lt; 2e-16 ***
post_pandemic         -0.0666476  0.1073761  -0.621 0.534818    
dig_mun:post_pandemic  0.2953475  0.1628510   1.814 0.069773 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8168 on 8777 degrees of freedom
Multiple R-squared:  0.09827,   Adjusted R-squared:  0.09734 
F-statistic: 106.3 on 9 and 8777 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">interact_plot</span>(<span class="at">model =</span> modela_pan_int1, <span class="at">pred =</span> <span class="st">"log_ingresos_real"</span>, <span class="at">modx =</span> <span class="st">"post_pandemic"</span>, </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">interval =</span> <span class="cn">TRUE</span>, <span class="at">x.label =</span> <span class="st">"Income"</span>, <span class="at">y.label =</span> <span class="st">"OPE"</span>, </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">modx.labels =</span> <span class="fu">c</span>(<span class="st">"Pre-Pandemic"</span>, <span class="st">"Post-Pandemic"</span>))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>plot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">interact_plot</span>(<span class="at">model =</span> modela_pan_int2, <span class="at">pred =</span> <span class="st">"dig_mun"</span>, <span class="at">modx =</span> <span class="st">"post_pandemic"</span>, </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">interval =</span> <span class="cn">TRUE</span>, <span class="at">x.label =</span> <span class="st">"Digitalised Municipality"</span>, <span class="at">y.label =</span> <span class="st">"OPE"</span>, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">modx.labels =</span> <span class="fu">c</span>(<span class="st">"Pre-Pandemic"</span>, <span class="st">"Post-Pandemic"</span>))</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>modelk_pan <span class="ot">&lt;-</span> <span class="fu">lm</span>(use <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> post_pandemic, <span class="at">data =</span> EOP_nona)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelk_pan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = use ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + ope + intpol + post_pandemic, data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42265 -0.17663 -0.07214  0.17407  0.76328 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.180066   0.046318   3.888 0.000102 ***
dig_mun            0.200175   0.035086   5.705 1.20e-08 ***
log_ingresos_real -0.025465   0.003590  -7.094 1.40e-12 ***
sex                0.016760   0.005199   3.224 0.001269 ** 
age               -0.001754   0.000156 -11.248  &lt; 2e-16 ***
SES                0.003210   0.003466   0.926 0.354412    
education          0.026914   0.001587  16.955  &lt; 2e-16 ***
ope                0.011849   0.003103   3.819 0.000135 ***
intpol             0.082989   0.005736  14.468  &lt; 2e-16 ***
post_pandemic      0.027145   0.005137   5.284 1.29e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2375 on 8777 degrees of freedom
Multiple R-squared:  0.158, Adjusted R-squared:  0.1572 
F-statistic: 183.1 on 9 and 8777 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>modela_pan_int3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(use <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> post_pandemic <span class="sc">+</span> log_ingresos_real <span class="sc">*</span> post_pandemic , <span class="at">data =</span> EOP_nona)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela_pan_int3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = use ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + ope + intpol + post_pandemic + log_ingresos_real * 
    post_pandemic, data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42076 -0.17667 -0.07225  0.17453  0.76505 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      0.239200   0.060404   3.960 7.55e-05 ***
dig_mun                          0.200090   0.035083   5.703 1.21e-08 ***
log_ingresos_real               -0.029097   0.004307  -6.755 1.52e-11 ***
sex                              0.016794   0.005198   3.231 0.001240 ** 
age                             -0.001756   0.000156 -11.261  &lt; 2e-16 ***
SES                              0.003245   0.003465   0.936 0.349144    
education                        0.026907   0.001587  16.952  &lt; 2e-16 ***
ope                              0.011647   0.003105   3.751 0.000177 ***
intpol                           0.083257   0.005738  14.509  &lt; 2e-16 ***
post_pandemic                   -0.094152   0.079706  -1.181 0.237542    
log_ingresos_real:post_pandemic  0.007411   0.004860   1.525 0.127303    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2374 on 8776 degrees of freedom
Multiple R-squared:  0.1583,    Adjusted R-squared:  0.1573 
F-statistic:   165 on 10 and 8776 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>modela_pan_int4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(use <span class="sc">~</span> dig_mun <span class="sc">+</span> log_ingresos_real <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> SES <span class="sc">+</span> education <span class="sc">+</span> ope <span class="sc">+</span> intpol <span class="sc">+</span> post_pandemic <span class="sc">+</span> dig_mun <span class="sc">*</span> post_pandemic , <span class="at">data =</span> EOP_nona)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela_pan_int4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = use ~ dig_mun + log_ingresos_real + sex + age + 
    SES + education + ope + intpol + post_pandemic + dig_mun * 
    post_pandemic, data = EOP_nona)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42750 -0.17680 -0.07158  0.17475  0.75816 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            0.2319383  0.0484691   4.785 1.74e-06 ***
dig_mun                0.1111118  0.0428849   2.591 0.009587 ** 
log_ingresos_real     -0.0250638  0.0035889  -6.984 3.08e-12 ***
sex                    0.0165765  0.0051954   3.191 0.001425 ** 
age                   -0.0017574  0.0001559 -11.275  &lt; 2e-16 ***
SES                    0.0031184  0.0034634   0.900 0.367938    
education              0.0269142  0.0015863  16.967  &lt; 2e-16 ***
ope                    0.0116326  0.0031010   3.751 0.000177 ***
intpol                 0.0832944  0.0057327  14.530  &lt; 2e-16 ***
post_pandemic         -0.0838341  0.0311957  -2.687 0.007216 ** 
dig_mun:post_pandemic  0.1706703  0.0473206   3.607 0.000312 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2373 on 8776 degrees of freedom
Multiple R-squared:  0.1593,    Adjusted R-squared:  0.1583 
F-statistic: 166.3 on 10 and 8776 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> <span class="fu">interact_plot</span>(<span class="at">model =</span> modela_pan_int3, <span class="at">pred =</span> <span class="st">"log_ingresos_real"</span>, <span class="at">modx =</span> <span class="st">"post_pandemic"</span>, </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">interval =</span> <span class="cn">TRUE</span>, <span class="at">x.label =</span> <span class="st">"Income"</span>, <span class="at">y.label =</span> <span class="st">"Use of Mun. Website"</span>, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">modx.labels =</span> <span class="fu">c</span>(<span class="st">"Pre-Pandemic"</span>, <span class="st">"Post-Pandemic"</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>plot3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span> <span class="fu">interact_plot</span>(<span class="at">model =</span> modela_pan_int4, <span class="at">pred =</span> <span class="st">"dig_mun"</span>, <span class="at">modx =</span> <span class="st">"post_pandemic"</span>, </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">interval =</span> <span class="cn">TRUE</span>, <span class="at">x.label =</span> <span class="st">"Digitalised Municipality"</span>, <span class="at">y.label =</span> <span class="st">"Use of Mun. Website"</span>, </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">modx.labels =</span> <span class="fu">c</span>(<span class="st">"Pre-Pandemic"</span>, <span class="st">"Post-Pandemic"</span>))</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>plot4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Quarto_Digital_Index_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>